export const COLOR_IDENTITY_NONE = "NONE";
export const COLOR_IDENTITY_WHITE = "WHITE";
export const COLOR_IDENTITY_RED = "RED";
export const COLOR_IDENTITY_GREEN = "GREEN";
export const COLOR_IDENTITY_BLACK = "BLACK";
export const COLOR_IDENTITY_BLUE = "BLUE";

export const COLOR_IDENTITY_LABEL_GRADIENT_COLOR = {
  [COLOR_IDENTITY_NONE]: "#DFDEDE",
  [COLOR_IDENTITY_WHITE]: "#F2F1EF",
  [COLOR_IDENTITY_RED]: "#FFE0D3",
  [COLOR_IDENTITY_GREEN]: "#CFDDCD",
  [COLOR_IDENTITY_BLACK]: "#BAB4B5",
  [COLOR_IDENTITY_BLUE]: "#A9CCE5"
  // GOLD: #DCBB78
};

export const COLOR_IDENTITY_CARD_GRADIENT_COLOR = {
  [COLOR_IDENTITY_NONE]: "#DDDDDF",
  [COLOR_IDENTITY_WHITE]: "#F6FCFC",
  [COLOR_IDENTITY_RED]: "#C5432B",
  [COLOR_IDENTITY_GREEN]: "#324F33",
  [COLOR_IDENTITY_BLACK]: "#403232",
  [COLOR_IDENTITY_BLUE]: "#1971CE"
  // GOLD: #D9CC71
};
