export const COLOR_IDENTITY_NONE = "NONE";
export const COLOR_IDENTITY_WHITE = "WHITE";
export const COLOR_IDENTITY_RED = "RED";
export const COLOR_IDENTITY_GREEN = "GREEN";
export const COLOR_IDENTITY_BLACK = "BLACK";
export const COLOR_IDENTITY_BLUE = "BLUE";

export const COLOR_IDENTITY_LABEL_GRADIENT_COLOR = {
  [COLOR_IDENTITY_NONE]: "#d1d5da",
  [COLOR_IDENTITY_WHITE]: "#c2c7a5",
  [COLOR_IDENTITY_RED]: "#F2B09A",
  [COLOR_IDENTITY_GREEN]: "#ADCEBD",
  [COLOR_IDENTITY_BLACK]: "#A09B98",
  [COLOR_IDENTITY_BLUE]: "#85B7D8"
};

export const COLOR_IDENTITY_CARD_GRADIENT_COLOR = {
  [COLOR_IDENTITY_NONE]: "#bbbbbb",
  [COLOR_IDENTITY_WHITE]: "#dcdecd",
  [COLOR_IDENTITY_RED]: "#E04C32",
  [COLOR_IDENTITY_GREEN]: "#007C46",
  [COLOR_IDENTITY_BLACK]: "#54504D",
  [COLOR_IDENTITY_BLUE]: "#227DAC"
};
