name: Default Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - deploy

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ github.ref }}-${{ github.sha }}-node-modules

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ github.ref }}-${{ github.sha }}-node-modules
      - run: npm test

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ github.ref }}-${{ github.sha }}-node-modules
      - run: npm run build
      - uses: actions/cache@v1
        with:
          path: ./build
          key: ${{ github.ref }}-${{ github.sha }}-build

  deploy:
    needs: [build]
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v1
        with:
          path: ./build
          key: ${{ github.ref }}-${{ github.sha }}-build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: build
