name: Test and Build

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ github.ref }}-${{ github.sha }}-node-modules

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ github.ref }}-${{ github.sha }}-node-modules
      - run: npm test

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ github.ref }}-${{ github.sha }}-node-modules
    - run: npm run build
